import foto from "../img/foto.png";

export const itens = [
    {nome: "algum nome",
    descricao: "alguma descricao1",
    imagem: foto,
    cor: "black"}, 
    {nome: "segundo nome",
    descricao: "outra descricao2",
    imagem: foto,
    cor: "black"},
    {nome: "terceiro nome",
    descricao: "outra descricao3",
    imagem: foto,
    cor: "black"},
    {nome: "quarto nome",
    descricao: "outra descricao4",
    imagem: foto,
    cor: "black"},
    {nome: "quinto nome",
    descricao: "outra descricao5",
    imagem: foto,
    cor: "black"},
    {nome: "sexto nome",
    descricao: "outra descricao6",
    imagem: foto,
    cor: "black"},
    {nome: "sétimo nome",
    descricao: "outra descricao7",
    imagem: foto,
    cor: "black"},
    {nome: "oitavo nome",
    descricao: "outra descricao8",
    imagem: foto,
    cor: "black"}
  ];