export const itens = [
    {nome: "algum nome",
    descricao: "alguma descricao1",
    imagem: "../img/foto.png"},
    {nome: "segundo nome",
    descricao: "outra descricao2",
    imagem: "../img/foto.png"},
    {nome: "terceiro nome",
    descricao: "outra descricao3",
    imagem: "../img/foto.png"},
    {nome: "quarto nome",
    descricao: "outra descricao4",
    imagem: "../img/foto.png"},
    {nome: "quinto nome",
    descricao: "outra descricao5",
    imagem: "../img/foto.png"},
    {nome: "sexto nome",
    descricao: "outra descricao6",
    imagem: "../img/foto.png"},
    {nome: "sétimo nome",
    descricao: "outra descricao7",
    imagem: "../img/foto.png"},
    {nome: "oitavo nome",
    descricao: "outra descricao8",
    imagem: "../img/foto.png"}
  ];